before_install:
- sudo apt-get update 
- sudo apt-get install texlive-latex-extra texlive-fonts-recommended pandoc make
script:
- make
branch: master
deploy:
  provider: releases
  api_key:
    secure: $GITHUB_OAUTH_TOKEN
  file:
  - ./out/resume.pdf
  skip_cleanup: true
  on:
    tags: true
branch: master
