name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run
      run: |
        sudo apt-get update
        sudo apt-get install --yes texlive-latex-extra texlive-fonts-recommended lmodern pandoc make
        make
