name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: |
          sudo apt-get update
          sudo apt-get install --yes texlive-latex-extra texlive-fonts-recommended lmodern pandoc make
          make
      
      - uses: actions/upload-artifact@v1
        with:
          name: resume.pdf
          path: build/resume.pdf
